### ISSUE TITLE
Hi you, Ask about the server and the client.

### ISSUE THREAD

**Issue by tam241992** [ShrineGames/NetworkingTutorial#2]
You can create server and client individual, to run server then connect to client when server run?
Communication between server and client is separate not same project.
Thank you!

**Comment by shahneil** [comment]
Yes you can run the server and client as separate instances - but with Mirror they're still in the same project.

**Comment by tam241992** [comment]
> Yes you can run the server and client as separate instances - but with Mirror they're still in the same project.

I very like video of you, hope you have more game RPG basic, ideas and meaning like simple RPG role playing.
I have subscribed to your channel.
Thank very much.
